bot:
  guild: ${DISCORD_GUILD:691227762102501436}
  token: ${DISCORD_TOKEN}

logging:
  level:
    goodgartic.mrclean: debug

# TODO: Move the database file to a mounted Docker volume later
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:h2:file:~/mrclean}

  jpa:
    hibernate:
      ddl-auto: update