// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MrClean.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MrClean.Migrations
{
    [DbContext(typeof(MrCleanDbContext))]
    partial class MrCleanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MrClean.Models.MessageFilter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChannelsSpecification")
                        .HasColumnType("text");

                    b.Property<long>("Delay")
                        .HasColumnType("bigint");

                    b.Property<string>("Pattern")
                        .HasColumnType("text");

                    b.Property<decimal?>("RepostChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("RolesSpecification")
                        .HasColumnType("text");

                    b.Property<string>("UsersSpecification")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MessageFilters");
                });
#pragma warning restore 612, 618
        }
    }
}
